/*
 * JDialog.java
 *
 * Created on 13 de septiembre de 1999, 07:19 PM
 */
import java.awt.*;
import java.util.*;
/**
 *
 * @author  MFG
 */
public class AboutDlg extends javax.swing.JDialog {
    
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jButton1;
     
    /** Creates new form JDialog */
    public AboutDlg(java.awt.Frame parent, boolean modal) {
       
        super(parent, modal);
        initComponents();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		
        getContentPane().setLayout(null);

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel1.setText("Desarrollado por Manuel Fernandez");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 220, 190, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel11.setText("MFG Corp Solitaire");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 130, 140, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel12.setText("Version 1.0");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 150, 140, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel13.setText("Copyright (C) 2002");
        jLabel13.setToolTipText("null");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 170, 140, 20);

		jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(240, 260, 81, 26);



        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(333, 315));
        setLocation((screenSize.width-333)/2,(screenSize.height-300)/2);
    	About abo = new About();
        abo.setSize(335,110);
        getContentPane().add(abo);
    	
		
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        setVisible(false);
        dispose();
    }
    
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
        // Add your handling code here:
    }
    
	public class About extends javax.swing.JComponent {
        
        public void paint(Graphics g)
        {
            Toolkit tk = Toolkit.getDefaultToolkit();
            Image im = tk.getImage("about.jpg");
            g.drawImage(im,0,0,335,110,this);
        }
        
    }    
    
    
}
