import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.UIManager;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.applet.*;

// An applet that is eventually to contain a game of Solitaire
public class Solitaire extends Applet
{

    SolitaireComponent	sol;
    CardPictureStore	store;
	
	public void init()
	{
		store = new CardPictureStore(this,"Cards");
		Image im = this.getImage(getClass().getResource("tapete.jpg"));
		this.showStatus("Loading tapete image...");
		this.showStatus("Load Complete...");
		sol = new SolitaireComponent(store);
        this.setLayout(new BorderLayout());
		this.add(sol, "Center");
        sol.Deal();
	}
	
  
	public static void main(String args[])
	{
		
		   // and populate with the LnF's

		new SolitaireFrame().show();
	}

}

class SolitaireFrame extends javax.swing.JFrame {
    
    SolitaireComponent	sol;
    CardPictureStore	store;
    AboutDlg 		abo;
    
    /** Creates new form SolitaireFrame */
    public SolitaireFrame() {
   
        store = new CardPictureStore("Cards");
		sol = new SolitaireComponent(store);
		Toolkit tk = Toolkit.getDefaultToolkit();
        WindowsGUI();
        initComponents();
        getContentPane().setLayout(new BorderLayout());
		getContentPane().add(sol, "Center");
        sol.Deal();
        
    }
    
    public void WindowsGUI()
    {
    	javax.swing.UIManager myUIMgr = new javax.swing.UIManager();
        javax.swing.UIManager.LookAndFeelInfo[] installedLnFs = myUIMgr.getInstalledLookAndFeels();
        
        for (int i = 0; i < installedLnFs.length; i++)
        {
        	if(installedLnFs[i].getName() == "Windows")
        	{
        		try
                {
         		   myUIMgr.setLookAndFeel(installedLnFs[i].getClassName());
        		}
        		catch(Exception e)
        		{
            		e.printStackTrace();
        		}
        	}
        }
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        getContentPane().setLayout(null);

        setTitle("Solitaire");
      //  setIconImage(getClass().getResource("/icon.gif"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jMenu1.setText("Game");
        jMenuItem1.setText("Deal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem7);
        jMenuBar1.add(jMenu1);
        jMenu3.setText("Help");
        jMenuItem8.setText("About Solitaire");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });

        jMenu3.add(jMenuItem8);
        jMenuBar1.add(jMenu3);
        setJMenuBar(jMenuBar1);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(730, 730));
        setLocation((screenSize.width-730)/2,(screenSize.height-730)/2);
    }

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
        abo = new AboutDlg(this,true);
        abo.show();
        // Add your handling code here:
    }

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
         System.exit(0);
        // Add your handling code here:
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        sol.Deal();
        // Add your handling code here:
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }
    
    /**
     * @param args the command line arguments
     */
       
    
    // Variables declaration - do not modify
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration
    
}
